language: node_js
node_js:
- '5'
notifications:
  slack: garlictech:hWAwcbpZceCN9v67hEn1ynIR
install:
- npm install
script:
- npm run build
deploy:
  provider: npm
  email: contact@garlictech.com
  on:
    tags: true
  api_key:
    secure: KzupXRvK3p5mF1wIx77MaOtfzZ0FM2aGHjYcNE03kJEfQBUurdkiASC7l/pKzkd5w4LaTofjOveydVwzTUhTkfx8inEdiSkXjdsgQluRkA830ASC1hcgtkYKno8kOaEeBCzwW6OnWFiID6ijhB1UUt0iXLvdT4XqRFQ5lkalQM85djFjletZq0+/eZkSK+eErBHYc1qhJ9b9mi9zikm4dgT0T5qewFpnexYMfhrCpYDLYNwilmihVY5xeZ0ZBdZT/40wLxed+ymCTHgTryN4FQo/de5TuEvYzjxhtj0vda1vkoeDUvi2dFEwhMg0SjHaM03qwaCx4+7hMF2z667KrH3jBNe5maFa2kc2Tmv4VN0MUSBrrszbtPnE7QyYlxM8WPrBnCyAzNrAS9xgpVjV3LBskcwzRMsx2MpubRsDiywPlW+VA6nIvJj1+rUUfI9qB8L+1lo1eJI6jJazxgG4lAIxbcGZ4EIVJOTPvtbP7vIbTWa39r3X7bRLsgSFkU2QovpdJ0RTCxGmXlDgLuFIlLfcEMRn6Kk281L7Ju0etLUCn4GJisDmlq2o4Mo7o8s0jc7tPEWc4pW0GKKH5xdRV+U9DazwZ9dWtjQtzWfUurgHB/ChPpDCEgGoNL/zWrL2UtWfCBG8MU2Qtx/Fpig/aX81yH78t4P6kwAYACm+QQo=
