language: node_js
node_js:
- '5'
notifications:
  slack:
    garlictech:
      secure: q4bycNEuVkYmYQk6eBOsgrNLxwie20GPbgU4kbYcDqybi1EwzuRWfrbQgYIwkLOQ0sIBHC+lGgqv5JfPC8aATZ1RrI6IEUD91OdnslCkbhVdjQlGmeOfh1wbd1GdrYJQIOox1kuHJzZGczDlnpTrvUAStbmmuCH7BgQbIxFWW3VHkMdB9ERR3iU1yuhye9qJfsIpKoLfxz0D1LL9YQBzbXbFcUFauEwevjhzYoCLn/KQDy0PJTHB46dYK5XoL8mO0Z6GNEJEt5BKyTnY8azTBxbXv5tOI3QSN0ZMOhVgUjt2cEST7C+Z5uO+N8Tse8x9qXWX0vim+xcp3/E8Xp5aYmrwnPRBztQNG/tBwEaPo0majPBMnZq27XkEYWkLgGSI4QqXQpVYa17Kfl3gT29Mjja+mbPGiKNy8KJIhBIckW9remI55v6zI/2lf3dXNITBGTHZ2LcSX9DLqokZRcbyeDUiF1TKeNqY8Y+b6TAw4LdyGvGlTKJg4+L60zwf+I79oLZ0Qj3+xg8YEYZCmkX4OmdfKwJJQpYwAts7LkgRUGtbDrmrqbObNxYNAF9cpPDmd+huPZmouNBKYJPlbY4VNgEVYQA2OwWrsL5afe1wF9QxUSaptiKQneTKyTmBi/khQRgauXZJjgeVE1qeeqyMxQLHQ+z4klPfFEsU0qznwVU=
install:
- npm install
script:
- npm run build
branches:
  only:
  - master
  - stable
deploy:
  provider: npm
  email: contact@garlictech.com
  on:
    tags: true
  api_key:
    secure: KzupXRvK3p5mF1wIx77MaOtfzZ0FM2aGHjYcNE03kJEfQBUurdkiASC7l/pKzkd5w4LaTofjOveydVwzTUhTkfx8inEdiSkXjdsgQluRkA830ASC1hcgtkYKno8kOaEeBCzwW6OnWFiID6ijhB1UUt0iXLvdT4XqRFQ5lkalQM85djFjletZq0+/eZkSK+eErBHYc1qhJ9b9mi9zikm4dgT0T5qewFpnexYMfhrCpYDLYNwilmihVY5xeZ0ZBdZT/40wLxed+ymCTHgTryN4FQo/de5TuEvYzjxhtj0vda1vkoeDUvi2dFEwhMg0SjHaM03qwaCx4+7hMF2z667KrH3jBNe5maFa2kc2Tmv4VN0MUSBrrszbtPnE7QyYlxM8WPrBnCyAzNrAS9xgpVjV3LBskcwzRMsx2MpubRsDiywPlW+VA6nIvJj1+rUUfI9qB8L+1lo1eJI6jJazxgG4lAIxbcGZ4EIVJOTPvtbP7vIbTWa39r3X7bRLsgSFkU2QovpdJ0RTCxGmXlDgLuFIlLfcEMRn6Kk281L7Ju0etLUCn4GJisDmlq2o4Mo7o8s0jc7tPEWc4pW0GKKH5xdRV+U9DazwZ9dWtjQtzWfUurgHB/ChPpDCEgGoNL/zWrL2UtWfCBG8MU2Qtx/Fpig/aX81yH78t4P6kwAYACm+QQo=
