language: node_js
node_js:
- '5'
notifications:
  slack: garlictech:hWAwcbpZceCN9v67hEn1ynIR
before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
install:
- npm install
script:
- npm run build
deploy:
  provider: npm
  email: contact@garlictech.com
  on:
    tags: true
  api_key:
    secure: bIjpHBpXiDcYCxw2Hx/wqkO9kqHL3jM+/IgrT7SttBf+NVjerkTrWmrAlUf9hqDyczflMGLynDFJOnTiD9u6mU1bDDpRqCVERQccY1SC3OUtiWCvauE+0LjyC4hgxaVsQSgMcz6Pn3Doqu4+aqC6ypoeR2/LtKtTEmW0YPIqr+tsDFN/RQJNcrJDC3B9KNVd2VqdSwn7POmoA1g3H/5UOSxq4iWc+RY97HPBLUJPoXi0xUEHUWINe9LlqBzzmMelgafTC7qwayq1VPq3II/IWL2VKHRjTckgjjNgSxKOIxEMtDTNBxNWdgU38dVcKdpaBivMgvxJZdqFA/B9l2E3tvuK/wNL95yG6M/5Bu2J4m7LP8FVG2e3wA4xVOyyBNkh37IkAhwkF8PtQnZ5yPQ3x6I8HRQkikTykl8m+i8JDG1c/m4V6OiCUHja52NYP2VogG+vVyhCRJrYM3fVngj5kciyn1Q6OLVCyvyKiK5lp0lm9KRzg7vdQFQVG9fV0HnH5+syVWRq5iDDJg3xtvnGPeyT269+bwVCNMzVf8OGjf3/9dfoXd5uOVCJyGtiKjhN1t/cRiF7c8GjfVBOBdcWKL1qhSK+hsI4podpY2k/3kzfY3mdXSsyiEfFaI6gbUOS3Druzwo3QulSDFuZaCNMAxRycUDHbriqVeK6gsCI9WA=
env:
  global:
    secure: F69HkC9/a8ssq+kpAu4q3fQE0RxwKTfcRRHoHQKM/BVu/E9W3m8s1pX1z1DD0/byAZ1XkXVUF1SQrUtocSgtVgy1KZecwsM4PbA7kL0O8NdiXsC8DDXg39B+izJtu2igx0tOMLYFHztX932s+r9qH7V/zh0depC/tP/Pg6dQs7lZJCCUd1mtuLCT3lCzJYr9K7Oz9uoFHhjD2U3jgVsxQlbRLmmNTTSEjSj4l7HyCdqcw2ckgZpQvK9ST/nMJ3rmzcaCcXx+VMowkx46Qvss/ocree/1madIcTYcs5wAfRicxbvZXMK+54kwqLJfJ4KkqYCnZYSk1Dimtjr07d13wc7tVeBkQnGMVGMzYVXriGVSF178Z+9cqcj2e8XiueuRgspGUNwNgQ0GmHNf5A9Lou1DtB2/xFW+AtceLBbCe8D5vBe0foQkXalaCyodsQm6SpMCSPiATY325R90VFeyy+r4LzxySlWvYEgYCrAf3P0IIEEA8GfotPsvvCD+teDLsOTlaovBfTsHhu0YrUJJqX9ReFbhUAnE9yeTTkYdooEIhBrDimfF8gXoACeIgDIyrrYU6z6h+YL71LCAE1qSj8EJi9VAdE7KUtYaH1Y2JQuUfNY4ay1Caq8lwXlaXO49g6eimgLVGmSBhcNe7SX34NFJn32qG04EyfmmNWAuaro=
